# GitHub Actions Workflow responsible for template-clean like updating CLA contract url. This workflow is supposed to be triggered automatically
# when a new template-based repository has been created.

name: Template Clean Up
on:
  push:

jobs:

  # Run cleaning process only if workflow is triggered by the non micronaut-project/micronaut-project-template repository.
  template-cleanup:
    name: Template Cleanup
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'micronaut-project-template'
    permissions:
      contents: read
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      # Cleanup project
      - name: Cleanup
        run: |
          # Update CLA url in CONTRIBUTING.md
          sed -i "s|micronaut-projects/micronaut-project-template|$GITHUB_REPOSITORY|" CONTRIBUTING.md
          sed -i "s|project-template|${GITHUB_REPOSITORY:29}|" README.md
          sed -i "s|project-template|${GITHUB_REPOSITORY:29}|" gradle.properties
          sed -i "s|project-template|${GITHUB_REPOSITORY:29}|" CONTRIBUTING.md
          sed -i "s|project-template|${GITHUB_REPOSITORY:29}|" MAINTAINING.md
          sed -i "s|micronaut-projects/micronaut-project-template|$GITHUB_REPOSITORY|" SECURITY.md
          sed -i "s|project-template|${GITHUB_REPOSITORY:29}|" project-template/build.gradle
          sed -i "s|project-template|${GITHUB_REPOSITORY:29}|" project-template-bom/build.gradle
          sed -i "s|project-template|${GITHUB_REPOSITORY:29}|" buildSrc/src/main/groovy/io.micronaut.build.internal.project-template-module.gradle
          git mv project-template/ "micronaut-${GITHUB_REPOSITORY:29}/"
          git mv project-template-bom/ "micronaut-${GITHUB_REPOSITORY:29}-bom/"
          git mv buildSrc/src/main/groovy/io.micronaut.build.internal.project-template-module.gradle "buildSrc/src/main/groovy/io.micronaut.build.internal.${GITHUB_REPOSITORY:29}-module.gradle"
          git mv buildSrc/src/main/groovy/io.micronaut.build.internal.project-template-base.gradle "buildSrc/src/main/groovy/io.micronaut.build.internal.${GITHUB_REPOSITORY:29}-base.gradle"
          # Remove clean up template
          rm -rf  .github/workflows/template-cleanup.yml

      # Save modified files
      - name: Create cleanup patch
        run: |
          git add .
          git diff --cached --binary > template-cleanup.patch

      # Upload cleanup patch
      - name: Upload cleanup patch
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: template-cleanup-patch
          path: template-cleanup.patch

  template-cleanup-push:
    name: Push Template Cleanup
    runs-on: ubuntu-latest
    needs: template-cleanup
    if: github.event.repository.name != 'micronaut-project-template'
    permissions:
      contents: write
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      # Download cleanup patch
      - name: Download cleanup patch
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: template-cleanup-patch

      # Commit modified files
      - name: Commit files
        run: |
          git apply --index template-cleanup.patch
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Template cleanup"

      # Push changes
      - name: Push changes
        run: git push origin "HEAD:${GITHUB_REF}"
